import { componentCode } from "@/data/component-code";

export const categories = [
  "Buttons",
  "Cards",
  "Inputs",
  "Loaders",
  "AI Interfaces",
  "Navigation",
  "Badges",
  "Modals",
  "Effects",
] as const;

export type ComponentCategory = (typeof categories)[number];
export type Difficulty = "Beginner" | "Intermediate" | "Advanced";
export type ComponentSlug = keyof typeof componentCode;

export type ComponentItem = {
  slug: ComponentSlug;
  name: string;
  description: string;
  category: ComponentCategory;
  tags: string[];
  difficulty: Difficulty;
  code: string;
  usage: string;
  accessibility?: string;
  featured?: boolean;
};

export const components: ComponentItem[] = [
  {
    slug: "neon-gradient-button",
    name: "Neon Gradient Button",
    description: "A compact call-to-action with a glowing gradient edge and dark inner surface.",
    category: "Buttons",
    tags: ["cta", "gradient", "glow"],
    difficulty: "Beginner",
    code: componentCode["neon-gradient-button"],
    usage: `<NeonGradientButton>Launch interface</NeonGradientButton>`,
    accessibility: "Use clear button text and keep it inside a form or action region where the intent is obvious.",
  },
  {
    slug: "glass-command-card",
    name: "Glass Command Card",
    description: "A glassmorphism command card for product shortcuts, palettes, and agent actions.",
    category: "Cards",
    tags: ["glass", "command", "shortcut"],
    difficulty: "Beginner",
    code: componentCode["glass-command-card"],
    usage: `<GlassCommandCard />`,
    accessibility: "Keyboard hints should match the supported platform shortcut in your app.",
  },
  {
    slug: "ai-chat-input",
    name: "AI Chat Input",
    description: "A responsive prompt composer with textarea, label, and high-contrast send button.",
    category: "Inputs",
    tags: ["ai", "chat", "form"],
    difficulty: "Intermediate",
    code: componentCode["ai-chat-input"],
    usage: `<AiChatInput />`,
    accessibility: "The textarea includes a label for screen readers; connect submit behavior to your own handler.",
    featured: true,
  },
  {
    slug: "streaming-response-bubble",
    name: "Streaming Response Bubble",
    description: "A conversational response card with subtle animated streaming indicators.",
    category: "AI Interfaces",
    tags: ["streaming", "chat", "response"],
    difficulty: "Beginner",
    code: componentCode["streaming-response-bubble"],
    usage: `<StreamingResponseBubble />`,
    accessibility: "Use aria-live in your app shell when the message content updates dynamically.",
  },
  {
    slug: "prompt-badge",
    name: "Prompt Badge",
    description: "A small status badge for prompt state, tuning, review, or evaluation labels.",
    category: "Badges",
    tags: ["prompt", "status", "badge"],
    difficulty: "Beginner",
    code: componentCode["prompt-badge"],
    usage: `<PromptBadge />`,
    accessibility: "Do not rely on the color dot alone; keep the text label visible.",
  },
  {
    slug: "agent-step-timeline",
    name: "Agent Step Timeline",
    description: "A simple ordered timeline for AI agents, build systems, and workflow progress.",
    category: "AI Interfaces",
    tags: ["agent", "timeline", "steps"],
    difficulty: "Intermediate",
    code: componentCode["agent-step-timeline"],
    usage: `<AgentStepTimeline />`,
    accessibility: "The ordered list preserves step order for assistive technologies.",
    featured: true,
  },
  {
    slug: "floating-nav-dock",
    name: "Floating Nav Dock",
    description: "A pill-shaped navigation dock with translucent depth and compact labels.",
    category: "Navigation",
    tags: ["nav", "dock", "glass"],
    difficulty: "Intermediate",
    code: componentCode["floating-nav-dock"],
    usage: `<FloatingNavDock />`,
    accessibility: "Keep an aria-label on the nav and use real links for each destination.",
  },
  {
    slug: "glow-loader",
    name: "Glow Loader",
    description: "A three-dot animated loader with turquoise, violet, and warm orange glow accents.",
    category: "Loaders",
    tags: ["loader", "animation", "status"],
    difficulty: "Beginner",
    code: componentCode["glow-loader"],
    usage: `<GlowLoader />`,
    accessibility: "The preview uses role status and an aria-label so loading state is announced.",
  },
  {
    slug: "copy-code-card",
    name: "Copy Code Card",
    description: "A compact code surface for snippets, component recipes, and copy actions.",
    category: "Cards",
    tags: ["code", "copy", "snippet"],
    difficulty: "Beginner",
    code: componentCode["copy-code-card"],
    usage: `<CopyCodeCard />`,
    accessibility: "Wire the copy action to visible feedback after copying.",
  },
  {
    slug: "source-citation-card",
    name: "Source Citation Card",
    description: "A citation card for grounded AI responses and research-backed interfaces.",
    category: "AI Interfaces",
    tags: ["source", "citation", "ai"],
    difficulty: "Beginner",
    code: componentCode["source-citation-card"],
    usage: `<SourceCitationCard />`,
    accessibility: "Figure and figcaption create a useful relationship between quote and source.",
  },
  {
    slug: "model-switcher",
    name: "Model Switcher",
    description: "A segmented control for fast, smart, and deep model modes.",
    category: "AI Interfaces",
    tags: ["model", "switcher", "control"],
    difficulty: "Intermediate",
    code: componentCode["model-switcher"],
    usage: `<ModelSwitcher />`,
    accessibility: "For production, manage selected state and expose it with aria-pressed or radio semantics.",
    featured: true,
  },
  {
    slug: "token-usage-pill",
    name: "Token Usage Pill",
    description: "A compact usage indicator for token budgets, metering, and AI billing surfaces.",
    category: "Badges",
    tags: ["tokens", "meter", "usage"],
    difficulty: "Beginner",
    code: componentCode["token-usage-pill"],
    usage: `<TokenUsagePill />`,
    accessibility: "Pair the visual meter with text so the value is understandable without color.",
  },
  {
    slug: "gradient-split-button",
    name: "Gradient Split Button",
    description: "A primary action with a separate options trigger for deploys, exports, and publish flows.",
    category: "Buttons",
    tags: ["split", "deploy", "action"],
    difficulty: "Intermediate",
    code: componentCode["gradient-split-button"],
    usage: `<GradientSplitButton />`,
    accessibility: "Give the secondary trigger an aria-label that describes the menu it opens.",
  },
  {
    slug: "glass-metric-card",
    name: "Glass Metric Card",
    description: "A compact KPI card with a progress rail for evals, usage, and model quality signals.",
    category: "Cards",
    tags: ["metric", "dashboard", "glass"],
    difficulty: "Beginner",
    code: componentCode["glass-metric-card"],
    usage: `<GlassMetricCard />`,
    accessibility: "Keep the numeric value as visible text and do not rely only on the progress bar.",
    featured: true,
  },
  {
    slug: "neural-search-input",
    name: "Neural Search Input",
    description: "A rounded search field for command palettes, component galleries, and prompt libraries.",
    category: "Inputs",
    tags: ["search", "command", "input"],
    difficulty: "Beginner",
    code: componentCode["neural-search-input"],
    usage: `<NeuralSearchInput />`,
    accessibility: "The input includes a screen-reader label; wire slash-key focus behavior in your app shell.",
  },
  {
    slug: "voice-wave-loader",
    name: "Voice Wave Loader",
    description: "An audio-style loader for transcription, generation, and voice agent interfaces.",
    category: "Loaders",
    tags: ["audio", "voice", "loader"],
    difficulty: "Beginner",
    code: componentCode["voice-wave-loader"],
    usage: `<VoiceWaveLoader />`,
    accessibility: "The loader uses role status with an audio processing label.",
  },
  {
    slug: "context-menu-panel",
    name: "Context Menu Panel",
    description: "A floating action menu for editor surfaces, AI workspaces, and command-rich tools.",
    category: "Navigation",
    tags: ["menu", "actions", "floating"],
    difficulty: "Intermediate",
    code: componentCode["context-menu-panel"],
    usage: `<ContextMenuPanel />`,
    accessibility: "For production, connect this panel to menu button semantics and keyboard navigation.",
  },
  {
    slug: "shortcut-key",
    name: "Shortcut Key",
    description: "A clean keyboard shortcut badge for command hints, docs, and toolbars.",
    category: "Badges",
    tags: ["shortcut", "keyboard", "docs"],
    difficulty: "Beginner",
    code: componentCode["shortcut-key"],
    usage: `<ShortcutKey />`,
    accessibility: "Pair shortcuts with text actions so users do not need to memorize key combinations.",
  },
  {
    slug: "modal-shell",
    name: "Modal Shell",
    description: "A focused confirmation dialog shell with clear hierarchy and paired actions.",
    category: "Modals",
    tags: ["modal", "dialog", "confirm"],
    difficulty: "Intermediate",
    code: componentCode["modal-shell"],
    usage: `<ModalShell />`,
    accessibility: "Use a real dialog primitive in production to trap focus and restore focus on close.",
  },
  {
    slug: "status-toast-stack",
    name: "Status Toast Stack",
    description: "A stacked notification pattern for build, deploy, and sync events.",
    category: "Effects",
    tags: ["toast", "status", "feedback"],
    difficulty: "Beginner",
    code: componentCode["status-toast-stack"],
    usage: `<StatusToastStack />`,
    accessibility: "Announce new toast messages with an aria-live region in the app shell.",
  },
  {
    slug: "icon-pulse-button",
    name: "Icon Pulse Button",
    description: "A compact icon action with a soft pulse for agent runs, recording, and quick launch controls.",
    category: "Buttons",
    tags: ["icon", "pulse", "agent"],
    difficulty: "Beginner",
    code: componentCode["icon-pulse-button"],
    usage: `<IconPulseButton />`,
    accessibility: "The icon-only button includes an aria-label; keep that label specific to the action.",
  },
  {
    slug: "pricing-tier-card",
    name: "Pricing Tier Card",
    description: "A small pricing card for open-source tiers, creator plans, and product packaging.",
    category: "Cards",
    tags: ["pricing", "tier", "saas"],
    difficulty: "Beginner",
    code: componentCode["pricing-tier-card"],
    usage: `<PricingTierCard />`,
    accessibility: "Use semantic text for price and plan details so the tier is understandable without visuals.",
  },
  {
    slug: "file-dropzone",
    name: "File Dropzone",
    description: "A drag-and-drop upload surface for assets, screenshots, and UI reference files.",
    category: "Inputs",
    tags: ["upload", "file", "dropzone"],
    difficulty: "Intermediate",
    code: componentCode["file-dropzone"],
    usage: `<FileDropzone />`,
    accessibility: "The dropzone is a label wrapping a file input, making it keyboard and screen-reader reachable.",
  },
  {
    slug: "progress-stepper",
    name: "Progress Stepper",
    description: "A horizontal stepper for onboarding, generation pipelines, and design workflows.",
    category: "Navigation",
    tags: ["steps", "progress", "workflow"],
    difficulty: "Intermediate",
    code: componentCode["progress-stepper"],
    usage: `<ProgressStepper />`,
    accessibility: "The ordered list preserves step sequence; add current-step state in production.",
  },
  {
    slug: "notification-bell",
    name: "Notification Bell",
    description: "A glass notification trigger with a warm unread indicator.",
    category: "Badges",
    tags: ["notification", "bell", "status"],
    difficulty: "Beginner",
    code: componentCode["notification-bell"],
    usage: `<NotificationBell />`,
    accessibility: "The button has an aria-label; announce unread counts in nearby text when available.",
  },
  {
    slug: "code-tab-switcher",
    name: "Code Tab Switcher",
    description: "A compact tab control for switching between preview, source code, and usage examples.",
    category: "Effects",
    tags: ["tabs", "code", "switcher"],
    difficulty: "Beginner",
    code: componentCode["code-tab-switcher"],
    usage: `<CodeTabSwitcher />`,
    accessibility: "For production tabs, add roving focus and aria-selected state management.",
  },
  {
    slug: "agent-memory-card",
    name: "Agent Memory Card",
    description: "A compact memory summary card for personalized agents and workspace context.",
    category: "AI Interfaces",
    tags: ["agent", "memory", "context"],
    difficulty: "Intermediate",
    code: componentCode["agent-memory-card"],
    usage: `<AgentMemoryCard />`,
    accessibility: "Keep saved memories visible as text and provide controls for editing or deleting them in production.",
  },
  {
    slug: "eval-radar-card",
    name: "Eval Radar Card",
    description: "A live evaluation card for accuracy, latency, grounding, and release-readiness signals.",
    category: "Cards",
    tags: ["eval", "metrics", "quality"],
    difficulty: "Intermediate",
    code: componentCode["eval-radar-card"],
    usage: `<EvalRadarCard />`,
    accessibility: "Expose each metric as text and avoid using the gradient bar as the only signal.",
  },
  {
    slug: "prompt-version-select",
    name: "Prompt Version Select",
    description: "A styled select control for pinning prompt versions in AI release workflows.",
    category: "Inputs",
    tags: ["prompt", "version", "select"],
    difficulty: "Beginner",
    code: componentCode["prompt-version-select"],
    usage: `<PromptVersionSelect />`,
    accessibility: "The select is wrapped by a visible label so the control has a clear name.",
  },
  {
    slug: "api-key-field",
    name: "API Key Field",
    description: "A guarded credential input for settings screens, integrations, and developer tools.",
    category: "Inputs",
    tags: ["api", "security", "settings"],
    difficulty: "Beginner",
    code: componentCode["api-key-field"],
    usage: `<ApiKeyField />`,
    accessibility: "Use a precise label and pair save actions with visible success or error feedback.",
  },
  {
    slug: "inline-alert-banner",
    name: "Inline Alert Banner",
    description: "A compact warning banner for usage spikes, sync issues, and workflow interruptions.",
    category: "Effects",
    tags: ["alert", "warning", "feedback"],
    difficulty: "Beginner",
    code: componentCode["inline-alert-banner"],
    usage: `<InlineAlertBanner />`,
    accessibility: "Keep the alert message visible as text and announce dynamic alerts with aria-live in production.",
  },
  {
    slug: "confidence-meter",
    name: "Confidence Meter",
    description: "A multi-signal confidence card for grounded AI answers, eval reviews, and release checks.",
    category: "AI Interfaces",
    tags: ["confidence", "eval", "signals"],
    difficulty: "Intermediate",
    code: componentCode["confidence-meter"],
    usage: `<ConfidenceMeter />`,
    accessibility: "Each signal includes a text value, so progress bars are not the only source of meaning.",
    featured: true,
  },
  {
    slug: "workflow-breadcrumb",
    name: "Workflow Breadcrumb",
    description: "A pill breadcrumb for agent workspaces, release flows, and nested product tools.",
    category: "Navigation",
    tags: ["breadcrumb", "workflow", "nav"],
    difficulty: "Beginner",
    code: componentCode["workflow-breadcrumb"],
    usage: `<WorkflowBreadcrumb />`,
    accessibility: "Use a nav landmark with a descriptive aria-label and real links for each parent route.",
  },
  {
    slug: "schema-field-row",
    name: "Schema Field Row",
    description: "A labeled schema input row for structured prompt builders and data-mapping interfaces.",
    category: "Inputs",
    tags: ["schema", "field", "form"],
    difficulty: "Beginner",
    code: componentCode["schema-field-row"],
    usage: `<SchemaFieldRow />`,
    accessibility: "The visible label names the input and the required badge is supplemented by text.",
  },
  {
    slug: "skeleton-card",
    name: "Skeleton Card",
    description: "A loading placeholder card for dashboards, streamed summaries, and async previews.",
    category: "Loaders",
    tags: ["skeleton", "loading", "placeholder"],
    difficulty: "Beginner",
    code: componentCode["skeleton-card"],
    usage: `<SkeletonCard />`,
    accessibility: "The wrapper uses role status and an aria-label to describe the loading state.",
  },
  {
    slug: "stat-strip",
    name: "Stat Strip",
    description: "A dense row of metrics for build dashboards, model monitoring, and usage reports.",
    category: "Cards",
    tags: ["stats", "metrics", "dashboard"],
    difficulty: "Beginner",
    code: componentCode["stat-strip"],
    usage: `<StatStrip />`,
    accessibility: "The definition-list structure preserves label and value relationships.",
  },
  {
    slug: "command-hint-bar",
    name: "Command Hint Bar",
    description: "A compact shortcut strip for command palettes, editors, and agent workspaces.",
    category: "Badges",
    tags: ["shortcut", "keyboard", "command"],
    difficulty: "Beginner",
    code: componentCode["command-hint-bar"],
    usage: `<CommandHintBar />`,
    accessibility: "Use real keyboard labels and pair each shortcut with a visible action name.",
  },
  {
    slug: "toggle-setting-row",
    name: "Toggle Setting Row",
    description: "A settings row with a clear label, helper text, and active toggle state.",
    category: "Inputs",
    tags: ["toggle", "settings", "form"],
    difficulty: "Beginner",
    code: componentCode["toggle-setting-row"],
    usage: `<ToggleSettingRow />`,
    accessibility: "Expose toggle state with aria-pressed or switch semantics in production.",
  },
  {
    slug: "avatar-stack",
    name: "Avatar Stack",
    description: "A small collaborator stack for reviews, presence, and team-owned workflows.",
    category: "Badges",
    tags: ["avatar", "presence", "team"],
    difficulty: "Beginner",
    code: componentCode["avatar-stack"],
    usage: `<AvatarStack />`,
    accessibility: "Provide full names in accessible labels when initials represent real collaborators.",
  },
  {
    slug: "empty-state-panel",
    name: "Empty State Panel",
    description: "A friendly empty state with a primary action for variant, file, or project creation.",
    category: "Cards",
    tags: ["empty", "state", "cta"],
    difficulty: "Beginner",
    code: componentCode["empty-state-panel"],
    usage: `<EmptyStatePanel />`,
    accessibility: "Keep the empty-state message and action visible as text.",
  },
  {
    slug: "release-checklist",
    name: "Release Checklist",
    description: "A compact checklist for publish gates, QA passes, and handoff readiness.",
    category: "Cards",
    tags: ["release", "checklist", "quality"],
    difficulty: "Beginner",
    code: componentCode["release-checklist"],
    usage: `<ReleaseChecklist />`,
    accessibility: "Use text labels for every check so completion is not communicated by color alone.",
  },
  {
    slug: "prompt-diff-viewer",
    name: "Prompt Diff Viewer",
    description: "A small diff surface for prompt changes, review notes, and agent edits.",
    category: "AI Interfaces",
    tags: ["prompt", "diff", "review"],
    difficulty: "Intermediate",
    code: componentCode["prompt-diff-viewer"],
    usage: `<PromptDiffViewer />`,
    accessibility: "Include plus and minus markers as text so additions and removals remain clear.",
  },
  {
    slug: "color-token-swatch",
    name: "Color Token Swatch",
    description: "A token list for documenting product colors, theme palettes, and design variables.",
    category: "Effects",
    tags: ["color", "tokens", "theme"],
    difficulty: "Beginner",
    code: componentCode["color-token-swatch"],
    usage: `<ColorTokenSwatch />`,
    accessibility: "Show color values as readable text instead of relying on swatches alone.",
  },
  {
    slug: "integration-status-grid",
    name: "Integration Status Grid",
    description: "A three-column status grid for connected services, deploy targets, and docs sync.",
    category: "Cards",
    tags: ["integration", "status", "dashboard"],
    difficulty: "Beginner",
    code: componentCode["integration-status-grid"],
    usage: `<IntegrationStatusGrid />`,
    accessibility: "Pair every status dot with a visible service name and state label.",
  },
  {
    slug: "usage-sparkline-card",
    name: "Usage Sparkline Card",
    description: "A compact usage chart card for token volume, traffic, or event trends.",
    category: "Cards",
    tags: ["usage", "sparkline", "metrics"],
    difficulty: "Intermediate",
    code: componentCode["usage-sparkline-card"],
    usage: `<UsageSparklineCard />`,
    accessibility: "Include the numeric trend as text because the bars are decorative.",
    featured: true,
  },
  {
    slug: "data-pipeline-card",
    name: "Data Pipeline Card",
    description: "A simple horizontal pipeline for data prep, agent workflows, and release steps.",
    category: "AI Interfaces",
    tags: ["pipeline", "data", "workflow"],
    difficulty: "Intermediate",
    code: componentCode["data-pipeline-card"],
    usage: `<DataPipelineCard />`,
    accessibility: "Keep step names visible and preserve the sequence in source order.",
  },
  {
    slug: "approval-action-panel",
    name: "Approval Action Panel",
    description: "A review panel with assignee chips and paired approval actions for launch workflows.",
    category: "AI Interfaces",
    tags: ["approval", "review", "workflow"],
    difficulty: "Intermediate",
    code: componentCode["approval-action-panel"],
    usage: `<ApprovalActionPanel />`,
    accessibility: "Keep both action labels explicit and expose approval state as readable text.",
  },
  {
    slug: "segmented-filter-tabs",
    name: "Segmented Filter Tabs",
    description: "A compact filter control with counts for dashboards, galleries, and release queues.",
    category: "Navigation",
    tags: ["tabs", "filter", "count"],
    difficulty: "Beginner",
    code: componentCode["segmented-filter-tabs"],
    usage: `<SegmentedFilterTabs />`,
    accessibility: "For production, manage active state with tab or radio semantics and visible labels.",
  },
  {
    slug: "latency-budget-card",
    name: "Latency Budget Card",
    description: "A stacked performance card for queue, model, and render timing budgets.",
    category: "Cards",
    tags: ["latency", "performance", "metrics"],
    difficulty: "Intermediate",
    code: componentCode["latency-budget-card"],
    usage: `<LatencyBudgetCard />`,
    accessibility: "Every timing value is shown as text so the bars are supporting visuals only.",
    featured: true,
  },
  {
    slug: "webhook-event-log",
    name: "Webhook Event Log",
    description: "A dense event log for webhook delivery, sync status, and integration health.",
    category: "Cards",
    tags: ["webhook", "events", "status"],
    difficulty: "Beginner",
    code: componentCode["webhook-event-log"],
    usage: `<WebhookEventLog />`,
    accessibility: "Use readable event names, time elements, and visible status codes for each row.",
  },
  {
    slug: "cost-estimate-card",
    name: "Cost Estimate Card",
    description: "A compact billing estimate with line items for token-heavy AI runs.",
    category: "Cards",
    tags: ["cost", "billing", "tokens"],
    difficulty: "Beginner",
    code: componentCode["cost-estimate-card"],
    usage: `<CostEstimateCard />`,
    accessibility: "Use a definition list so each cost item keeps its label and value relationship.",
  },
  {
    slug: "dataset-upload-queue",
    name: "Dataset Upload Queue",
    description: "A file queue for prompt datasets, eval fixtures, and design reference uploads.",
    category: "Inputs",
    tags: ["upload", "dataset", "queue"],
    difficulty: "Intermediate",
    code: componentCode["dataset-upload-queue"],
    usage: `<DatasetUploadQueue />`,
    accessibility: "Each file state is visible as text, with progress bars treated as supporting visuals.",
  },
  {
    slug: "agent-status-ribbon",
    name: "Agent Status Ribbon",
    description: "A compact status ribbon for showing the current phase of an agent workflow.",
    category: "Badges",
    tags: ["agent", "status", "workflow"],
    difficulty: "Beginner",
    code: componentCode["agent-status-ribbon"],
    usage: `<AgentStatusRibbon />`,
    accessibility: "Keep the current status label visible and update it through live regions when dynamic.",
    featured: true,
  },
  {
    slug: "agent-handoff-card",
    name: "Agent Handoff Card",
    description: "A transparent transfer surface for routing conversations between specialized agents with shared context.",
    category: "AI Interfaces",
    tags: ["agent", "handoff", "routing"],
    difficulty: "Intermediate",
    code: componentCode["agent-handoff-card"],
    usage: `<AgentHandoffCard />`,
    accessibility: "The source and destination agents, confidence, and transferred context are all represented as text.",
    featured: true,
  },
  {
    slug: "retrieval-health-card",
    name: "Retrieval Health Card",
    description: "A source-level health summary for RAG indexes, sync freshness, and retrieval quality.",
    category: "AI Interfaces",
    tags: ["retrieval", "rag", "observability"],
    difficulty: "Intermediate",
    code: componentCode["retrieval-health-card"],
    usage: `<RetrievalHealthCard />`,
    accessibility: "Each source includes textual freshness and quality values instead of relying on colored indicators.",
    featured: true,
  },
  {
    slug: "rate-limit-gauge",
    name: "Rate Limit Gauge",
    description: "A live capacity view for request and token budgets with reset timing and projected headroom.",
    category: "Cards",
    tags: ["api", "limits", "usage"],
    difficulty: "Intermediate",
    code: componentCode["rate-limit-gauge"],
    usage: `<RateLimitGauge />`,
    accessibility: "Every meter is paired with exact text values and a plainly stated reset time.",
    featured: true,
  },
  {
    slug: "context-window-meter",
    name: "Context Window Meter",
    description: "A token allocation breakdown for system instructions, conversation history, and retrieved sources.",
    category: "AI Interfaces",
    tags: ["tokens", "context", "observability"],
    difficulty: "Intermediate",
    code: componentCode["context-window-meter"],
    usage: `<ContextWindowMeter />`,
    accessibility: "Every segment has a visible label and token value, so the chart is supplementary rather than essential.",
    featured: true,
  },
  {
    slug: "human-checkpoint-card",
    name: "Human Checkpoint Card",
    description: "A high-impact approval gate that explains consequences before an agent continues.",
    category: "AI Interfaces",
    tags: ["approval", "agent", "safety"],
    difficulty: "Intermediate",
    code: componentCode["human-checkpoint-card"],
    usage: `<HumanCheckpointCard />`,
    accessibility: "Consequences are written as a list, action labels are explicit, and urgency is never communicated by color alone.",
    featured: true,
  },
  {
    slug: "tool-call-inspector",
    name: "Tool Call Inspector",
    description: "A live execution trace for agent tools, file operations, and long-running tasks.",
    category: "AI Interfaces",
    tags: ["agent", "tools", "observability"],
    difficulty: "Intermediate",
    code: componentCode["tool-call-inspector"],
    usage: `<ToolCallInspector />`,
    accessibility: "The ordered list preserves execution sequence, while every state and duration remains visible as text.",
    featured: true,
  },
  {
    slug: "multimodal-prompt-composer",
    name: "Multimodal Prompt Composer",
    description: "A polished prompt surface for combining instructions with images, documents, and audio context.",
    category: "AI Interfaces",
    tags: ["multimodal", "prompt", "attachments"],
    difficulty: "Intermediate",
    code: componentCode["multimodal-prompt-composer"],
    usage: `<MultimodalPromptComposer />`,
    accessibility: "The prompt has an accessible label, attachments form a named list, and every icon-only action has a specific label.",
    featured: true,
  },
  {
    slug: "structured-output-panel",
    name: "Structured Output Panel",
    description: "A schema-first response panel for inspecting typed fields, required values, and validation state.",
    category: "AI Interfaces",
    tags: ["schema", "structured-output", "validation"],
    difficulty: "Intermediate",
    code: componentCode["structured-output-panel"],
    usage: `<StructuredOutputPanel />`,
    accessibility: "A definition list preserves field-to-type relationships and validity is communicated with text rather than color alone.",
    featured: true,
  },
  {
    slug: "model-eval-comparison",
    name: "Model Eval Comparison",
    description: "A side-by-side model decision card balancing quality, latency, cost, and groundedness.",
    category: "AI Interfaces",
    tags: ["eval", "models", "comparison"],
    difficulty: "Intermediate",
    code: componentCode["model-eval-comparison"],
    usage: `<ModelEvalComparison />`,
    accessibility: "Every score and tradeoff is expressed as text, and the preferred candidate includes a visible label instead of color alone.",
    featured: true,
  },
  {
    slug: "tool-permission-card",
    name: "Tool Permission Card",
    description: "A transparent permission summary for file access, proposed writes, and external service boundaries.",
    category: "AI Interfaces",
    tags: ["tools", "permissions", "safety"],
    difficulty: "Intermediate",
    code: componentCode["tool-permission-card"],
    usage: `<ToolPermissionCard />`,
    accessibility: "Each permission includes a textual scope and an accessible allowed or blocked state, so switches never rely on color alone.",
    featured: true,
  },
  {
    slug: "model-fallback-route",
    name: "Model Fallback Route",
    description: "A resilience chain showing primary, fallback, and cached response routes with activation conditions.",
    category: "AI Interfaces",
    tags: ["models", "fallback", "reliability"],
    difficulty: "Intermediate",
    code: componentCode["model-fallback-route"],
    usage: `<ModelFallbackRoute />`,
    accessibility: "An ordered list preserves routing priority, and every model includes textual conditions and readiness state.",
    featured: true,
  },
  {
    slug: "prompt-test-case",
    name: "Prompt Test Case",
    description: "A focused evaluation card for test inputs, behavioral assertions, and prompt regression results.",
    category: "AI Interfaces",
    tags: ["prompt", "testing", "eval"],
    difficulty: "Intermediate",
    code: componentCode["prompt-test-case"],
    usage: `<PromptTestCase />`,
    accessibility: "Every assertion includes a visible Pass or Review label, and the summary reports an exact fraction.",
    featured: true,
  },
  {
    slug: "live-voice-session",
    name: "Live Voice Session",
    description: "A real-time voice panel with audio activity, streaming transcript, duration, and call controls.",
    category: "AI Interfaces",
    tags: ["voice", "realtime", "transcript"],
    difficulty: "Intermediate",
    code: componentCode["live-voice-session"],
    usage: `<LiveVoiceSession />`,
    accessibility: "Audio activity has a text alternative, the transcript is a polite live region, and controls use explicit labels.",
    featured: true,
  },
  {
    slug: "response-branch-navigator",
    name: "Response Branch Navigator",
    description: "A variant switcher for exploring concise, balanced, and detailed generations without losing context.",
    category: "AI Interfaces",
    tags: ["response", "variants", "branching"],
    difficulty: "Intermediate",
    code: componentCode["response-branch-navigator"],
    usage: `<ResponseBranchNavigator />`,
    accessibility: "Variant controls use tab semantics with an explicit selected state, and the active response is exposed as a tab panel.",
    featured: true,
  },
  {
    slug: "grounding-coverage-card",
    name: "Grounding Coverage Card",
    description: "A claim-level evidence audit showing citation coverage, source attribution, and unsupported statements.",
    category: "AI Interfaces",
    tags: ["grounding", "citations", "quality"],
    difficulty: "Intermediate",
    code: componentCode["grounding-coverage-card"],
    usage: `<GroundingCoverageCard />`,
    accessibility: "Coverage is exposed through progress semantics, exact text counts, and explicit source or citation-needed labels.",
    featured: true,
  },
  {
    slug: "feedback-score-card",
    name: "Feedback Score Card",
    description: "A reviewer feedback summary for beta launches, QA passes, and design reviews.",
    category: "Cards",
    tags: ["feedback", "review", "score"],
    difficulty: "Beginner",
    code: componentCode["feedback-score-card"],
    usage: `<FeedbackScoreCard />`,
    accessibility: "The score labels remain readable text so the grid is understandable without color.",
  },
];

export function getComponent(slug: string) {
  return components.find((component) => component.slug === slug);
}

export function getRelatedComponents(component: ComponentItem) {
  return components
    .filter((item) => item.slug !== component.slug && (item.category === component.category || item.tags.some((tag) => component.tags.includes(tag))))
    .slice(0, 3);
}
